/**
 * Resource Manager - Provides embedded FX core and plugin resources
 */

export class ResourceManager {
    /**
     * Get FX Core source
     */
    getFXCore(): string {
        return `/**
 * FX Core Framework - Minimal Build
 * Generated by FX Project Generator
 */

export interface FXNode {
    __id: string;
    __parent_id: string | null;
    __nodes: Record<string, FXNode>;
    __value: any;
    __type: string | null;
    __proto: string[];
    __behaviors: Map<string, any>;
    __instances: Map<string, any>;
    __effects: Function[];
    __watchers: Set<(nv: unknown, ov: unknown) => void>;
    __meta?: Record<string, any>;
}

export interface FXNodeProxy<V = any> {
    (path: string, value?: any): FXNodeProxy<any>;
    val(): V;
    val(newValue: any): FXNodeProxy<any>;
    watch(callback: (newValue: any, oldValue: any) => void): () => void;
    node(): FXNode;
    type(): string | null;
}

const nowId = () => Math.random().toString(36).slice(2) + Date.now().toString(36);

export class FXCore {
    private root: FXNode;
    public moduleLoader: any = null;

    constructor() {
        this.root = this.createNode("");
    }

    private createNode(id: string, parentId: string | null = null): FXNode {
        return {
            __id: id,
            __parent_id: parentId,
            __nodes: {},
            __value: undefined,
            __type: null,
            __proto: [],
            __behaviors: new Map(),
            __instances: new Map(),
            __effects: [],
            __watchers: new Set()
        };
    }

    resolvePath(path: string, root: FXNode = this.root): FXNode | undefined {
        if (!path) return root;

        const parts = path.split('.');
        let current = root;

        for (const part of parts) {
            if (!current.__nodes[part]) {
                return undefined;
            }
            current = current.__nodes[part];
        }

        return current;
    }

    setPath(path: string, value: any, root: FXNode = this.root): FXNode {
        if (!path) {
            root.__value = value;
            return root;
        }

        const parts = path.split('.');
        let current = root;

        for (let i = 0; i < parts.length; i++) {
            const part = parts[i];
            if (!current.__nodes[part]) {
                const nodeId = parts.slice(0, i + 1).join('.');
                current.__nodes[part] = this.createNode(nodeId, current.__id);
            }
            current = current.__nodes[part];
        }

        const oldValue = current.__value;
        current.__value = value;

        // Notify watchers
        for (const watcher of current.__watchers) {
            try {
                watcher(value, oldValue);
            } catch (e) {
                console.error('Watcher error:', e);
            }
        }

        return current;
    }

    proxy(): FXNodeProxy {
        const self = this;

        const createProxy = (basePath: string = ""): FXNodeProxy => {
            const handler = function(path: string, value?: any): FXNodeProxy {
                const fullPath = basePath ? \`\${basePath}.\${path}\` : path;

                if (value !== undefined) {
                    self.setPath(fullPath, value);
                }

                return createProxy(fullPath);
            } as FXNodeProxy;

            handler.val = function(newValue?: any) {
                if (newValue !== undefined) {
                    self.setPath(basePath, newValue);
                    return handler;
                }

                const node = self.resolvePath(basePath);
                return node?.__value;
            };

            handler.watch = function(callback: (nv: any, ov: any) => void) {
                let node = self.resolvePath(basePath);

                if (!node) {
                    node = self.setPath(basePath, undefined);
                }

                node.__watchers.add(callback);

                return () => {
                    node!.__watchers.delete(callback);
                };
            };

            handler.node = function() {
                return self.resolvePath(basePath) || self.setPath(basePath, undefined);
            };

            handler.type = function() {
                const node = self.resolvePath(basePath);
                return node?.__type || null;
            };

            return handler;
        };

        return createProxy();
    }

    getRoot(): FXNode {
        return this.root;
    }
}

export default FXCore;
`;
    }

    /**
     * Get FX V4 exports
     */
    getFXV4(): string {
        return `/**
 * FX Framework v4 - Exports
 */

export { FXCore, type FXNode, type FXNodeProxy } from './fx';
export default FXCore;
`;
    }

    /**
     * Get FX Disk files
     */
    getFXDisk(): { index: string; loader: string; vfs: string } {
        return {
            index: `/**
 * FX Disk - WASM Virtual File System
 */

export { FXDiskSyncLoader } from './loader';
export { FXDiskVFS } from './vfs';

export function patchFXWithPluginLoader(fx: any): void {
    // Patch FX to use the sync loader
    console.log('[FX-Disk] Loader patched');
}
`,
            loader: `/**
 * FX Disk Sync Loader
 */

export interface LoaderConfig {
    bundleUrl: string;
    cacheEnabled?: boolean;
}

export class FXDiskSyncLoader {
    private config: LoaderConfig;
    private loaded = false;

    constructor(config: LoaderConfig) {
        this.config = {
            cacheEnabled: true,
            ...config
        };
    }

    async init(): Promise<void> {
        // Load bundle
        console.log('[FX-Disk] Loading bundle:', this.config.bundleUrl);
        this.loaded = true;
    }

    load(path: string): any {
        if (!this.loaded) {
            console.warn('[FX-Disk] Loader not initialized');
            return null;
        }

        console.log('[FX-Disk] Loading:', path);
        return null;
    }

    isLoaded(): boolean {
        return this.loaded;
    }
}
`,
            vfs: `/**
 * FX Disk Virtual File System
 */

export class FXDiskVFS {
    private files = new Map<string, Uint8Array>();

    write(path: string, data: Uint8Array): void {
        this.files.set(path, data);
    }

    read(path: string): Uint8Array | null {
        return this.files.get(path) || null;
    }

    exists(path: string): boolean {
        return this.files.has(path);
    }

    delete(path: string): boolean {
        return this.files.delete(path);
    }

    list(prefix: string = ''): string[] {
        const result: string[] = [];
        for (const path of this.files.keys()) {
            if (path.startsWith(prefix)) {
                result.push(path);
            }
        }
        return result;
    }
}
`
        };
    }

    /**
     * Get plugin source
     */
    getPlugin(name: string): string {
        const plugins: Record<string, string> = {
            "fx-dom-dollar": this.getDomDollarPlugin(),
            "fx-cache": this.getCachePlugin(),
            "fx-orm": this.getOrmPlugin(),
            "fx-router": this.getRouterPlugin(),
            "fx-api": this.getApiPlugin(),
            "fx-markdown": this.getMarkdownPlugin(),
            "fx-flow": this.getFlowPlugin(),
            "fx-serialize": this.getSerializePlugin()
        };

        return plugins[name] || this.getGenericPlugin(name);
    }

    private getDomDollarPlugin(): string {
        return `/**
 * @fx-plugin fx-dom-dollar
 * @fx-global $dom
 */

export default function(fx: any) {
    const $dom = (selector: string) => {
        const elements = document.querySelectorAll(selector);
        return {
            elements: Array.from(elements),
            text(value?: string) {
                if (value !== undefined) {
                    this.elements.forEach(el => el.textContent = value);
                    return this;
                }
                return this.elements[0]?.textContent || '';
            },
            html(value?: string) {
                if (value !== undefined) {
                    this.elements.forEach(el => el.innerHTML = value);
                    return this;
                }
                return this.elements[0]?.innerHTML || '';
            },
            on(event: string, handler: EventListener) {
                this.elements.forEach(el => el.addEventListener(event, handler));
                return this;
            },
            addClass(className: string) {
                this.elements.forEach(el => el.classList.add(className));
                return this;
            },
            removeClass(className: string) {
                this.elements.forEach(el => el.classList.remove(className));
                return this;
            }
        };
    };

    (globalThis as any).$dom = $dom;
    return { name: 'dom-dollar', $dom };
}
`;
    }

    private getCachePlugin(): string {
        return `/**
 * @fx-plugin fx-cache
 * @fx-global $cache
 */

export default function(fx: any) {
    const cache = new Map<string, { value: any; expiry: number | null }>();

    const $cache = {
        set(key: string, value: any, ttl?: number) {
            const expiry = ttl ? Date.now() + ttl : null;
            cache.set(key, { value, expiry });
        },
        get(key: string) {
            const entry = cache.get(key);
            if (!entry) return undefined;
            if (entry.expiry && Date.now() > entry.expiry) {
                cache.delete(key);
                return undefined;
            }
            return entry.value;
        },
        delete(key: string) {
            return cache.delete(key);
        },
        clear() {
            cache.clear();
        },
        has(key: string) {
            return cache.has(key);
        }
    };

    (globalThis as any).$cache = $cache;
    return { name: 'cache', $cache };
}
`;
    }

    private getOrmPlugin(): string {
        return `/**
 * @fx-plugin fx-orm
 * @fx-global $db
 */

export default function(fx: any) {
    const $db = {
        tables: new Map<string, any[]>(),

        table(name: string) {
            if (!this.tables.has(name)) {
                this.tables.set(name, []);
            }
            return {
                insert: (data: any) => {
                    const table = this.tables.get(name)!;
                    const record = { id: Date.now(), ...data };
                    table.push(record);
                    return record;
                },
                find: (predicate?: (item: any) => boolean) => {
                    const table = this.tables.get(name)!;
                    return predicate ? table.filter(predicate) : [...table];
                },
                findOne: (predicate: (item: any) => boolean) => {
                    const table = this.tables.get(name)!;
                    return table.find(predicate);
                },
                update: (id: number, data: any) => {
                    const table = this.tables.get(name)!;
                    const index = table.findIndex(item => item.id === id);
                    if (index !== -1) {
                        table[index] = { ...table[index], ...data };
                        return table[index];
                    }
                    return null;
                },
                delete: (id: number) => {
                    const table = this.tables.get(name)!;
                    const index = table.findIndex(item => item.id === id);
                    if (index !== -1) {
                        return table.splice(index, 1)[0];
                    }
                    return null;
                }
            };
        }
    };

    (globalThis as any).$db = $db;
    return { name: 'orm', $db };
}
`;
    }

    private getRouterPlugin(): string {
        return `/**
 * @fx-plugin fx-router
 * @fx-global $router
 */

export default function(fx: any) {
    const routes = new Map<string, Function>();
    let currentRoute = '/';

    const $router = {
        add(path: string, handler: Function) {
            routes.set(path, handler);
        },
        navigate(path: string) {
            currentRoute = path;
            history.pushState({}, '', path);
            this.resolve();
        },
        resolve() {
            const handler = routes.get(currentRoute);
            if (handler) {
                handler();
            }
        },
        current() {
            return currentRoute;
        }
    };

    window.addEventListener('popstate', () => {
        currentRoute = window.location.pathname;
        $router.resolve();
    });

    (globalThis as any).$router = $router;
    return { name: 'router', $router };
}
`;
    }

    private getApiPlugin(): string {
        return `/**
 * @fx-plugin fx-api
 * @fx-global $api
 */

export default function(fx: any) {
    const $api = {
        baseUrl: '',

        setBaseUrl(url: string) {
            this.baseUrl = url;
        },

        async get(path: string, options?: RequestInit) {
            const response = await fetch(this.baseUrl + path, {
                method: 'GET',
                ...options
            });
            return response.json();
        },

        async post(path: string, data: any, options?: RequestInit) {
            const response = await fetch(this.baseUrl + path, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data),
                ...options
            });
            return response.json();
        },

        async put(path: string, data: any, options?: RequestInit) {
            const response = await fetch(this.baseUrl + path, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data),
                ...options
            });
            return response.json();
        },

        async delete(path: string, options?: RequestInit) {
            const response = await fetch(this.baseUrl + path, {
                method: 'DELETE',
                ...options
            });
            return response.json();
        }
    };

    (globalThis as any).$api = $api;
    return { name: 'api', $api };
}
`;
    }

    private getMarkdownPlugin(): string {
        return `/**
 * @fx-plugin fx-markdown
 * @fx-global $markdown
 */

export default function(fx: any) {
    const $markdown = {
        parse(text: string): string {
            let html = text;

            // Headers
            html = html.replace(/^### (.*$)/gm, '<h3>$1</h3>');
            html = html.replace(/^## (.*$)/gm, '<h2>$1</h2>');
            html = html.replace(/^# (.*$)/gm, '<h1>$1</h1>');

            // Bold
            html = html.replace(/\\*\\*(.*?)\\*\\*/g, '<strong>$1</strong>');

            // Italic
            html = html.replace(/\\*(.*?)\\*/g, '<em>$1</em>');

            // Code
            html = html.replace(/\\\`(.*?)\\\`/g, '<code>$1</code>');

            // Links
            html = html.replace(/\\[(.*?)\\]\\((.*?)\\)/g, '<a href="$2">$1</a>');

            // Paragraphs
            html = html.split('\\n\\n').map(p => \`<p>\${p}</p>\`).join('');

            return html;
        },

        render(text: string, container: HTMLElement) {
            container.innerHTML = this.parse(text);
        }
    };

    (globalThis as any).$markdown = $markdown;
    return { name: 'markdown', $markdown };
}
`;
    }

    private getFlowPlugin(): string {
        return `/**
 * @fx-plugin fx-flow
 * @fx-global $flow
 */

export default function(fx: any) {
    const $flow = {
        define(name: string) {
            const steps: Array<{ name: string; fn: Function }> = [];

            return {
                step(stepName: string, fn: Function) {
                    steps.push({ name: stepName, fn });
                    return this;
                },
                async run(input: any) {
                    let result = input;
                    for (const step of steps) {
                        console.log(\`[Flow:\${name}] Running: \${step.name}\`);
                        result = await step.fn(result);
                    }
                    return result;
                }
            };
        }
    };

    (globalThis as any).$flow = $flow;
    return { name: 'flow', $flow };
}
`;
    }

    private getSerializePlugin(): string {
        return `/**
 * @fx-plugin fx-serialize
 * @fx-global $serialize
 */

export default function(fx: any) {
    const $serialize = {
        stringify(obj: any): string {
            const seen = new WeakSet();
            return JSON.stringify(obj, (key, value) => {
                if (typeof value === 'object' && value !== null) {
                    if (seen.has(value)) {
                        return '[Circular]';
                    }
                    seen.add(value);
                }
                return value;
            });
        },

        parse(str: string): any {
            return JSON.parse(str);
        },

        clone<T>(obj: T): T {
            return JSON.parse(JSON.stringify(obj));
        }
    };

    (globalThis as any).$serialize = $serialize;
    return { name: 'serialize', $serialize };
}
`;
    }

    private getGenericPlugin(name: string): string {
        return `/**
 * @fx-plugin ${name}
 */

export default function(fx: any) {
    console.log('[${name}] Plugin loaded');
    return { name: '${name}' };
}
`;
    }
}
